spring:
  datasource:
    password: mypass
    url: jdbc:mariadb://localhost:3306/nation?verifyServerCertificate=false&useSSL=false&requireSSL=false
    username: root
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDB106Dialect
        format_sql: true
    show-sql: true
